### PR TITLE
Tanzu Service Mesh support by using appProtocol

### PR DESCRIPTION
**Pull request by ykhadilkar**
Adding appProtocol property for better TSM support

### CODE REVIEW

**Comment by dlinsley** [comment]
TSM is most likely Tanzu Service Mesh.  Having the `appProtocol` field isn't an absolute requirement, but intentionally naming the ports in the service definitions with their protocol is the most compatible way.  Instead of naming the ports with the port number, using `http` or `grpc` as names would be adequate.  More details here:  https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

Ideally this change would be on all service definitions, not just `customer-service`

**Comment by arey** [comment]
Hi @dlinsley thanks for your reply. Could you please add this change to all services for cohesion.
@odedia what is your recommandation in terme of k8s version this sample should be compatible?

**Comment by odedia** [comment]
TSM is indeed Tanzu Service Mesh, but I believe the change can benefit any service mesh going forward.
I think we need to set the minimum to 1.20 regardless because we're already at 1.23 as latest and support for Kubernetes os N-2.

**Comment by ykhadilkar** [comment]
Alright updated rest of the services **name to http**.

**Comment by arey** [comment]
Thank you @ykhadilkar

**Pull request merged**
